os:
  - linux

language: cpp

compiler:
  - gcc
  - clang

before_script:
  - date -u
  - uname -a
  - export J='-j3'

  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake swig swig2.0 libboost1.55-all-dev python-dev default-jdk python-nose

script:
  - cmake .
  - make

after_script:
  - cd pyTest
  - nosetests
