# Use container-based infrastructure
sudo: required
services:
  - docker

language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

# This results in a 2×2 build matrix.
# Where the variables are: os / compiler

addons:
  apt:
    sources: ['boost-latest', 'kalakris-cmake']
    packages:
    - cmake
    - swig
    - libboost1.55-all-dev
    - python-dev
    - python-nose

cache:
  # Caching Ubuntu packages
  apt: true

before_script:
  - env | sort  
  - date -u
  - uname -a

script:
  # build
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=`pwd`/../install -DSEQUENCEPARSER_PYTHON_VERSION=2.7
  - make
  - make install

  # tests
  - cd ${TRAVIS_BUILD_DIR}
  - export PYTHONPATH=$PYTHONPATH:`pwd`/install/lib/python2.7/site-packages
  - nosetests pyTest
