# Use container-based infrastructure
sudo: required
services:
  - docker

language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

env:
  global:
     - SEQUENCEPARSER_BUILD=${TRAVIS_BUILD_DIR}/build-sequenceparser
     - SEQUENCEPARSER_INSTALL=${TRAVIS_BUILD_DIR}/install-sequenceparser
     - CI_NODE_TOTAL=2
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.4

# This results in a 2×2x2 build matrix.
# Where the variables are: os / compiler / python version

addons:
  apt:
    sources: ['boost-latest', 'kalakris-cmake', 'pythonxy-devel']
    packages:
    - cmake
    - swig
    - libboost1.55-all-dev
    - python-dev
    - python-nose
    - python3-dev
    - python3-nose

cache:
  # Caching Ubuntu packages
  apt: true

before_script:
  - env | sort  
  - date -u
  - uname -a
  - if [ ${CC} = "gcc" ]; then ./tools/travis/gcc.install.coverage.sh; fi

script:
  - tools/travis/build.sh
  - tools/travis/launch_tests.sh

after_success:
  - if [ ${CC} = "gcc" ]; then ./tools/travis/gcc.generate.coverage.sh; fi
